
#
# With multiplier defaulting to 6 (maximum number of azs), there should
# be 42 allocations
# 0 - 10 should ne network
# 10 - 20 should be database / caching
# 20 - 30 should be compute resources
# 30 - 42 is left empty for arbitrary use
#
maximum_availability_zones: 5
component_version: 1.0.3
subnets:
  vpc_public:
    allocation: 0
    name: Public
    type: public
  compute:
    allocation: 1
    name: Compute
    type: private
  persistence:
    allocation: 2
    name: Persistence
    type: private
  cache:
    allocation: 3
    name: Cache
    type: private

enable_transit_vpc: false

#
# NACL Rules
#
# number: 50 - Rule number, rules must have different number values
# protocol: -1 - Port number (https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml)
# action: allow|deny - default is allow if key is not set
# cidr: 0.0.0.0/0 - default is 0.0.0.0/0 if no value is set
# from: 1024 - start of the port range, if just a single port just specify `from`
# to: 65535 - end of the port range

public_acl_rules:
  inbound:
    -
      number: 50
      from: 1024
      to: 65535
    -
      number: 51
      from: 22
    -
      number: 52
      from: 80
    -
      number: 53
      from: 443
    -
      number: 54
      protocol: 17
      from: 1024
      to: 65535
  outbound:
    -
      number: 50
      protocol: -1
      from: 1024
      to: 65535

securityGroups:
  ops:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        -
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
      ips:
        - ops
  dev:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        -
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
      ips:
        - dev
  backplane:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        -
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        -
          IpProtocol: tcp
          FromPort: 25
          ToPort: 25
        -
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
        -
          IpProtocol: udp
          FromPort: 123
          ToPort: 123
        -
          IpProtocol: udp
          FromPort: 123
          ToPort: 123
      ips:
        - stack
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 5666
          ToPort: 5666
      ips:
        - monitoring

ip_blocks:
  public:
    - 0.0.0.0/0
  ops:
    - 169.254.100.100/32
  dev:
    - 169.254.100.100/32
  monitoring:
    - 169.254.100.100/32

##### Configuration export or exported configuration (config_export) as key compared to (export_config) in template that means
##### Configuration OF export (or export configuration)
managed_accounts:
  ops:
    local: true

config_export:
  global:
    - maximum_availability_zones

lib_export:
  global:
    cfndsl:
      - az
